common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: gadget_collection_development
  username: postgres
  password: '123'

test:
  <<: *common
  database: gadget_collection_test
  username: postgres
  password: '123'

production:
  <<: *common
  database: gadget_collection_production
  username: postgres
  password: '123'
